---
title: "Milestones and Achievements 2017"
author:	Bryan Milstead
output: pdf_document
date:	"12 Dec 2016 - 30 Sep 2017"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Overall Rating: 
###CE 1 - Program Planning:
Rating: **self-rating: fully successful**

* Participate in ORD, AED, and MAB meetings and planning sessions
    - Details unknown (Target Date: Q2-Q4). 
        - **Midterm Pars: ongoing**
        - **Final Pars: fully successful**
* Participate in planning and refinements for SSWR 4.01C Cyanobacterial research (Target Date: Q2-Q4). 
    - Design the lakes database: work with colleagues to define what the database will include, how it will be stored, and what features it will include. (Target Date: Q3). 
        - **Midterm Pars: ongoing**
        - **Final Pars: fully successful**
    - Assist in the development of a research plan for the twice-weekly monitoring of RI lakes (Target Date: Q3). 
        - **Midterm Pars: ongoing**
        - **Final Pars: fully successful**

###CE 2 - Program Implementation: 
Rating: **self-rating: fully successful**

* Participate in implementation of SSWR 4.01C Cyanobacterial research 
    - Develop a relational database of all lakes in the coterminous United States for use in cyanobacteria monitoring and research.  
        - Database Development:  develop and populate the lakes database (Target Date: Q4). 
            - **Midterm Pars: ongoing**
            - **Final Pars: NLA2007 and NLA2012 reformatted and harmonized**
        - Document the Database:  write draft of basic metadata for the database. (Target Date: Q4). 
            - **Midterm Pars: ongoing**
            - **Final Pars: progressing but will not be complete until the database is ready**
        - Data Paper: begin drafting a publishable data paper describing the database features and how to access it. (Target Date: Q4). 
            - **Midterm Pars: ongoing**
            - **Final Pars: progressing but will not be complete until the database is ready**
    - Bloom modeling for SSWR 4.01c.  Assist with the analysis of the NLA 2007 phytoplankton and cyano toxin database. 
        - Organize NLA data and convert to an R database (Target Date: Q2). 
            - **Midterm Pars: partially done; change target to Q3**
            - **Final Pars: completed**
        - Analyze data using standard Ordination techniques (Target Date: Q3). 
            - **Midterm Pars: ongoing**
            - **Final Pars: completed**
        - Prepare abstract for a presentation at the 2017 ESA meeting in Portland (Target Date: Q2). 
            - **Midterm Pars: complete**
            - **Final Pars: completed**
    - Participate in proposed twice-weekly monitoring of cyanobacteria in Rhode Island Lakes
        - Field work as required (Target Date: Q3-Q4). 
            - **Midterm Pars: not started**
            - **Final Pars: ongoing / near completion**
        - Help with database development and analysis (Target Date: Q3-Q4). 
            - **Midterm Pars: not started** 
            - **Final Pars: awaiting data**
        - If possible, become trained in the collection, identification, and quantification of phytoplankton (Target Date: Q3-Q4).   
            - **Midterm Pars: not started**
            - **Final Pars: in progress; have worked with the Haney Lab (UNH) and other colleagues**

* Provide technical assistance to the Cyanobacteria Monitoring Collaborative
    - Assist with the implementation of the "cyanoScope" project
        - Paricipate in ongoing identification of sumitted photos (Target Date: Q2-Q4). 
            - **Midterm Pars: ongoing** 
            - **Final Pars: advancing; working on getting additional taxononmists to help**
        - Help with training and analysis as needed (Target Date: Q3-Q4). 
            - **Midterm Pars: ongoing**
            - **Final Pars: ongoing**
    - Attend quarterly meeting of the CMC in Chelmsford (Target Date: Q2-Q4). 
          - **Midterm Pars: ongoing** 
          - **Final Pars: ongoing** 
    - Work with the CMC to document and archive data for 2015 & 2016 (Target Date: Q2-Q4). 
          - **Midterm Pars: ongoing** 
          - **Midterm Pars: 2015 complete; 2016 is ongoing; now we have 2017 data also** 
    - Manage data collection for 2017 (Target Date: Q4). 
          - **Midterm Pars: ongoing** 
          - **Final Pars: template data entry forms provided; data have not been returned yet**
    - Assist with the analysis of 2015 & 2016 data (Target Date: Q2-Q4). 
          - **Midterm Pars: not started** 
          - **Final Pars: not started** 

###CE3 - Technical and Scientific Communication: 
Rating: **self-rating: fully successful**

* Present paper on the bloom modeling work at the Ecological Society of America meeting in Portland OR, August 6-11, 2017.  (Target Date: Q4). 
    - **Midterm Pars: abstract submitted; analysis in progress.**
    - **Final Pars: presentation cancelled after discovering problems with the dataset**
* Consisidering submitting an abstract based on the CMC work the 2017 (November) Harmful Algal Blooms Symposium in Baltimore (Target Date: Q3-Q4). 
    - **Midterm Pars: not started** 
    - **Final Pars: not done** 
* Draft data paper on lakes database for cyanobacteria research (Target Date: Q4). 
    - **Midterm Pars: not started** 
    - **Final Pars: not started**
* Draft manuscript for publication on the bloom modeling work (Target Date: Q4). 
    - **Midterm Pars: not started** 
    - **Final Pars: debating whether to move forward this due to problems with the NLA phytoplankton database** 

###CE 4 - Resource Management:
Rating: **self-rating: fully successful** 

* As needed, assist in budgeting for and procurement of equipment and services for SSWR 4.01C (Target date: Q2-Q4). 
    - **Midterm Pars: ongoing** 
    - **Final Pars: ongoing** 

###CE 5 - Professional Interactions and Teamwork:
Rating: **self-rating: exceeds expectation** 

* Forge new collaborations with URI and other academic institutions (Target date: Q2-Q4).
    - **Midterm Pars: ongoing**
    - **Final Pars: ongoing**
* Tentative: collaborate with the USGS to use the East Coast (combined MRB1 & MRB2) SPARROW model to analyze CMAQ scenarios (Target date: Q2-Q4). 
    - **Midterm Pars: research plan submitted to USGS** 
    - **Final Pars: completed** 
* Questionable: collaborate with NSF project in Chile to collate, document, and archive data from a 30 year field ecology project (Target date: Q2-Q4).  
    - **Midterm Pars: ongoing**
    - **Final Pars: ongoing**
* Participate on the AED Awards Board: serve as an MAB member to the board. Target date: Q2-Q4).  
    -**Midterm Pars: Task added April 2017.**
    - **Final Pars: ongoing**
* Extra Stuff
    - 201706: provided additional support and data to the Chesapeake Bay team from an analysis I did for them in 2014.
    - 201707: provided landscape and population to data for NLA lakes to Betsy Hilborn
